### PR TITLE
Do not claim that the working tree represents a release version

### PR DESCRIPTION
**Pull request by jglick**
Mark as a snapshot until the next release is actually done.

@reviewbybees

### CODE REVIEW

**Comment by ghost** [comment]
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
IIUC PRs should be still submitted to https://github.com/jenkinsci/xstream. Or not?

**Comment by jglick** [comment]
Not that I know of.

**Review by oleg-nenashev — APPROVED** [review]
🐝 I messed up something

**Comment by jglick** [comment]
@reviewbybees done

**Comment by jglick** [comment]
Can be closed once jenkinsci/jenkins#4944 is merged.

**Pull request closed without merging**
